api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-pubic
    httpClientTimeout: 300


certificatesResolvers:
  http:
    acme:
      email: bmoreno@yavirac.edu.ec
      storage: acme.json
      httpChallenge:
        entryPoint: http
